### PR TITLE
Daq patch panel

### PR DESCRIPTION
**Pull request by Pdada1**
DAQ-Patch Panel to connect various sensors to DAQ system. 
Contains the schematic for 1 complete sensor system, which will be duplicated for 3 total sensors per board
Sensor Ports
1-Power
2-Data 1
3-Data 2
4-Ground or Alternate Power

Schematic contains 50mA fuse for power port and RC low pass filter for data lines with a cutoff frequency or approx 20khz

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/21)

### CODE REVIEW

**Review by JasonBrave — DISMISSED** [review]
1. J2 and J5 can be merged into a 5 port screw terminal, as one common terminal for supplying power
2. Please keep schematics clean by align two resistor jumpers
3. For the two low-pass RC filters you only need one ground label each
4. Label low-pass filter cut-off frequency calculation beside filter
5. For resistor value we usually use 100R to represent 100 ohm, or 10k to represent 10 kilo-ohms
6. Please assign footprints before opening Pull Request

**Comment by Pdada1** [comment]
All previous changes addressed

**Review by BluCodeGH — DISMISSED** [review]
Looking good! Some thoughts:
1. Please ignore #auto_saved_files and ~files.lck from git.
1. Remove the Daq_Patch_Panel folder and the .txt files?
1. Why is the project called "DAQ_Power_Patch_PM_SC"? Can we rename it to "DAQ_Patch_Panel" pls?
1. DATA FILTER IN is a very confusing name. I would label your nets IN1 and OUT1
1. The resistor connection to ground needs to happen before the RC filter or the series resistor will mess it up.
1. You should specify that the resistors to ground are 1% tolerance in the value, "100R 1%".
1. You dont need to say "fuse" on the F1 value, we know its a fuse since its called F1
1. I'd move the power input screw terminal to the left of the schematic, right now it seems like an output.
1. Similarly I'd have the fuse wire coming out to the right of the power selection jumper so it seems like an output.
1. I'd arrange the power selection jumper so that the voltage increases as you rotate around, so like 5 at the top, the 10 to one side, 12 on the bottom, etc.
1. Please fix the location of the labels for the GND resitors so they are beside the resistors.
1. Resistors to GND and GND symbols should be pointing down. You can directly connect the RC filter GND to the capacitor and rotate the GND resistor jumper assembly by 90 degrees.
1. Now all of this looks good for a single channel, but we want to fit three channels per PCB. They make these triple-level terminal blocks that are a pretty cute solution, so you can have a 4-position one for input (and probably just a 6-pin flat screw terminal for output).
image
1. Something you can do to make the triplication easier is move all of the business stuff to a subsheet with heirarchical pins and then include three copies of that subsheet in the main schematic.
1. It would be really nice to daisy-chain power across these boards, so maybe add a second screw terminal with the voltage rails + gnd for the other side of the PCB?
1. The C1 footprint was incorrectly set to the 4-position jumper.
1. Your 3-way jumper footprints should all be for though-hole 0.1" pins to be bridged by something like this, not solder jumpers:
image
So the footprint I expect to see is this one:
image
1. Same goes for the 4-way jumper, I the current pads look like they are for SMD stuff not normal through-hole. To make it I'd start with the connector I sent above but add two more pads to form the + shape.

**Review by JasonBrave — DISMISSED** [review]
1. You haven't address this Jack's comment
> Why is the project called "DAQ_Power_Patch_PM_SC"? Can we rename it to "DAQ_Patch_Panel" pls?
2. J4 Label should be rotated to horizontal, and give it a proper name
3. I think for J3 it should be +5V at top too GND at bottom, so that daisy chain power wire does not need to cross over to each other
4. Footprint for JP2, JP7, JP11 need to be updated
5. Why there's a terminal block in the "Library"?

**Comment by Pdada1** [comment]
>     5. Why there's a terminal block in the "Library"?
It's because the terminal block standard library doesn't have a 6 pin screw terminal so that's the one I made using the pheonix datasheet

**Review by JasonBrave — CHANGES_REQUESTED** [review]
I think `TerminalBlock_Phoenix:TerminalBlock_Phoenix_MKDS-1,5-6-5.08_1x06_P5.08mm_Horizontal` is the footprint of the 6-pin screw terminal

**Review by JasonBrave — CHANGES_REQUESTED** [review]
Also the current layout of footprint of the 4-way jumper does not match the symbol, result in actual PCB the voltage selection is increasing counterclockwise.

**Comment by JasonBrave** [comment]
Otherwise LGTM

**Review by BluCodeGH — APPROVED** [review]
Agreed with Jason's points above. I think once all this is resolved you should be good to proceed with layout.
1. Total nit but you should have your power screw terminals ordered by voltage, so like 20V at the top and GND at the bottom. Also please make the GND symbol point down to differentiate it.
1. Look into "multi-unit symbols" for the sensor connector, it will let you lay it out as 3 identical 4-pin terminals called J4A, J4B, J4C.
1. Also in general when making symbols for generic parts like a screw terminal you shouldn't give the pins application-specific labels. The symbol should just have numbers and the netlabeles tell the reader what the pin is used for. That way the symbol can be reused in a different application.
1. Nit but pls keep things aligned, eg the heirarchical input labels in the sensor subsheet aren't aligned. Also IMO things generally look better if you give a bit of space between when a wire comes out of a part and turns a corner.
1. The pinout on the ground resistor jumpers should be consistent, ie pin 1 on JP6 connects to 100R but pin 1 on JP8 goes to the 10k.

**Review by BluCodeGH — APPROVED** [review]
This LGTM! Please move on to PCB design. I think because this is a fairly simple board you dont need to worry about separating layout and routing, feel free to do them together.

In terms of how the layout should look, we'll want to fit 4 of these side-by-side in the DAQ breifcase so the biggest thing to optimize for is width. You'll want to have your 12-pin input connector at the top, the power daisy-chain connectors on either side, and your 6-pin output connector on the bottom. Another mechanical concern is mounting to the DIN rail, we can probably add a footprint for something like https://www.digikey.ca/en/products/detail/phoenix-contact/1202713/348430 to make mounting super easy.

As always I've still got a few nits thought:
1. You'll actually need to flip one of your power connectors in the schematic so that when you have the PCBs side by side the connectors line up pin-to-pin. See how currently the connections would need to cross between the adjacent PCBs?
image
1. The 12 pin screw terminal doesn't have its footprint assigned
1. Your pins on the custom symbol shouldnt be crossing into the main body, compare against the power terminal symbol and see how the pins stick out a bit more. Also you could make that symbol a bit thinner, again more like the power terminal symbol.
1. The text on the resistor jumpers in the subsheet is irregular and overlapping. All text on schematics should be oriented horizontally, so I recommend laying it out like this:
image
You'll also notice I fixed the alignment of the GND text there, you can do that by editing the properties of just the "GND" text (not the whole symbol) and then setting the horizontal alignment to centered:
image

**Review by JasonBrave — DISMISSED** [review]
1. J1 and J2 are in wrong direction
2. Leave more space between SMD components in the back side, same for SMD components near J2
3. The space near J1 and J3 can be compressed

**Review by BluCodeGH — DISMISSED** [review]
Sorry, I dont think I quite got across what I was picturing for the layout. Does this image make more sense?
image
This way you can have a bunch of these side-by-side and hook up the power wires between them, and you have a nice open space for all your jumpers in the middle with the output at the bottom.

You also still need to flip around one of your power screw terminals for the jumpers between boards to work correctly.

Lastly I'll point out that its going to be very important that this board is well-labeled on the silkscreen, so I'd suggest spacing things out a bit more than your original layout did so you have room for that.

**Comment by BluCodeGH** [comment]
And honestly this might be a better layout since we want to pack these in pretty tightly:
image

**Review by BluCodeGH — DISMISSED** [review]
Looking much better! Comments on the current layout:
1. You board outline isn't quite aligned in the bottom left corner, so DRC is complaining. Also please add rounded corners, they are a small change that make boards look way more professional.
1. You should have a GND filled zone on the top and bottom copper layers.
1. We need a way to mount this board to the DIN rail in DAQ, I recommend adding a footprint for something like https://www.digikey.ca/en/products/detail/phoenix-contact/1202713/348430 for this.
1. Please make sure everything is nicely aligned. For example your voltage select jumpers are out of whack, and I dont think the screw terminals for the voltage passthrough are centered either.
1. Your dimensions are currently on the F.Cu layer which means they are going to be included in any exports to JLC, they need to be on the User.Drawings layer. Also I dont think your top dimension is correct?
1. I also recommend adding a vertical center line to user.drawings to help you make sure everything is lined up and centered nicely.
1. You need big, human-readable silkscreen labels on all your connectors + jumpers so an operator can set things up correctly without referencing the schematic.
1. You should use thicker traces to connect the power daisy-chain connectors since the first board might see a decent bit of current.
1. You should put a via to tie the RC filter's resistor and capacitor together close to each other rather than having make that long loop to the output through-hole and back.
1. The more you can tighten up the width of the board the better. If you show the .Courtyard layers you can see the physical boundaries of each component, so you can make the board outline just touch the two sides of the data output connector.
1. Making it shorter will also make things fit better inside DAQ. One obvious thing you can do is to put the power connectors much closer to the big 12-pin, but there's lots of other places you can save vertical space eg by moving more passives to the back.

**Comment by ManavToor** [comment]
Looking pretty good...

1. Some silkscreens are no on the board
image

2. The 5V is not connected
image

3. Silkscreens should not overlap with vias, it will distort the text
image

4. Try to avoid long traces running side by side like this. Good rule of thumb is to space have them 3x their width apart. 
image

5. I would move the copper fill to the outside of the board like this
image

6. Is this a random silkscreen on the back?
image

8. Try to avoid 90 degrees intersections
image

7. Can't have a board without the rocketry logo and your name :)

That's all for me!

**Comment by AshTheEngiqueer** [comment]
Looks pretty good, just found a few minor things
1. Good practice for traces to be centered on pads/holes afaik
image
2. Also there's a few instances of daisy-chaining where you're going trace -> hole -> trace - pretty sure it's better not to? Also this should be pretty quick to fix if it is an issue to begin with :)

**Comment by miles-milne** [comment]
LGTM! Just reporting a few errors from the DRC

1. Seems to be a missing connection here??
image


2. AHHH Clearance violation
image


3. Not sure if you had some specific design intent about this next part so feel free to correct me, but I feel like these resistors and capacitors around these through holes look a bit cramped, since there's a ton of free space above them. Also moving the resistors them upwards gives them better access to the ground pour (e.g. see the image below)
image
image

**Review by JasonBrave — DISMISSED** [review]
1. Remove random wire bit at 12 pin screw terminal pin 5 S2POWER
2. I suggest moving rocketry logo to between J1 and J3
3. JP1 S2POWER is not aligned to the hole center

**Review by JasonBrave — DISMISSED** [review]
1. The rocketry logo is overlapping with J3, move it closer to J1
2. Move J1 label outside the boundary of screw connector, J1 is covered by screw terminal right now

**Review by JasonBrave — APPROVED** [review]
LGTM if you don't mind rocketry logo and your name are in opposite direction

**Pull request merged**
