### PR TITLE
Spidey Sense V3

### PR DESCRIPTION
**Pull request by Darth-Raazi**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/19)

### CODE REVIEW

**Review by BluCodeGH — APPROVED** [review]
Functionally looks good! A few pretty-ness nitpicks:

1. Try to keep power symbols pointed up, not sideways. Also adding some padding rather than having wires turn right a way looks a bit cleaner imo:
image
2. If you press "x" you can flip a selected component (ie 2 pin screw terminal) in the X axis, so that pin number 1 is at the top
3. I think J9 is offset by one grid unit to the right compared to the other 3, which means it got the J9 label as opposed to J6. It's a tiny bit nicer if the labels are all in order.
4. Likewise I'd change up the connections to J10 such that the J2 connection goes to pin 1, J3 to pin 2, etc
5. You should label the wires going into/out of the thermocouple converter modules. Probably the best way to do so is to add net labels along the lines of "A+", "A-", "Aout", "B+", etc.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
PCB is looking good! A few tweaks to make:

1. The actual board dimensions don't need to be exactly the same, it's the hole spacing that's really important to keep. I'd probably tighten in the board outline so that the holes are in the corners (as opposed to the little gap on the top and bottom there is now). Also rounded corners are pretty imo :)
2. Even with the current board layout, and probably more so as you tighten it up, I'm worried that the daughter boards will hit the screw terminals. You can probably fix this by rotating the daughter boards 90 degrees and offsetting their vertical positions or something like that, whatever looks best to you.
3. Please add silkscreen labels to everything. Thermocouple + -, power + -, label (ABCD) the thermocouple connectors, converters and output pins, and specify the orientation of the daughter boards somehow. Also please remove the REF** silkscreens :stuck_out_tongue:

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Agreed with @BluCodeGH 's review.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks great! Just missing a few tiny things:
- Your name! And the date and the name of the board, along with the waterloo rocketry logo all on the top silkscreen. Take a look at any of the boards in canhw for inspiration, but at the end of the day make it look pretty to you!
- You could also probably make those screw terminal labels bigger. I find the 3d viewer (alt+3) very helpful in sizing stuff and right now those labels are dwarfed by those massive screw terminals lol

**Review by BluCodeGH — APPROVED** [review]
LGTM! We'll leave this PR open and close it when the board is ordered. I think we can lump this one with the RLCS CAN support board which should be finished soon.

**Review by QuantumManiac — APPROVED** [review]
Looks good to order!

**Comment by eliaskountouris** [comment]
looks good to me

**Comment by eliaskountouris** [comment]
Ordered, merging

**Pull request merged**
