### PR TITLE
Begin schematic mods for I2C.

### PR DESCRIPTION
**Pull request by kevinkwan23**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/7)

### CODE REVIEW

**Comment by AidanHa** [comment]
Schematics look fine to me. BTW who exactly is working on this board?

**Comment by zx100x100** [comment]
It has bounced around a bit, from now on Zachary is going to be the lead on it.

**Comment by ZTeper** [comment]
Should we have more meaningful silkscreen labels for the connectors? Names like J2, J3, etc. can be confusing. Meaningful silkscreen labels might be useful for people assembling/debugging the board.

**Comment by zx100x100** [comment]
J2, J3, ect are just the reference designators. Don't delete them, but it would be good to add silkscreen text for the connector pinout, as well as a channel number for each sensor connector.

**Comment by amihaila** [comment]
> J2, J3, ect are just the reference designators. Don't delete them, but it would be good to add silkscreen text for the connector pinout, as well as a channel number for each sensor connector.

I personally usually hide the reference designator silkscreen, and replace it with a meaningful name.

**Comment by ZTeper** [comment]
The first version of routing is finished. Please leave comments on how to improve the routing and the board in general. Please also leave suggestions about where to put copper pour areas (copper zones), since there currently are none.

**Comment by ZTeper** [comment]
> > J2, J3, ect are just the reference designators. Don't delete them, but it would be good to add silkscreen text for the connector pinout, as well as a channel number for each sensor connector.
> 
> I personally usually hide the reference designator silkscreen, and replace it with a meaningful name.

**Comment by ZTeper** [comment]
Hello PCB review folks. Let me know about:

- Whether we should switch to a 4-layer design. If so, what sorts of signals would go on each of the 4 layers?
- How I can improve the placement/routing on the current design.

Thanks.

**Comment by QuantumManiac** [comment]
So, I looked through the entire project instead of just the PCB layout out of boredom. Just a few things I noticed: 

- It seems that you are using a custom footprint named `C_0805_HandSoldering` for the capacitors. What's the difference between this and the `C_0805_2012Metric_Pad1.15x1.40mm_HandSolder` that comes in the KiCAD `Capacitor_SMD` library? Do the pads need to be larger?
image


- I'm not too familiar with this, but does the Instrumentation Amp need to have a KiCAD project file of its own? It's just a schematic, isn't it?
image


- I'm not that familiar with the standard for where to put custom footprints for projects, but should the custom footprints used be somewhere other than the main project directory? Perhaps in `lib` or a sub-folder in the project directory? @zx100x100, how's it usually done?  

- It seems that there are a few footprint and symbol libraries floating around in your project-specific libraries that have absolute paths on Alex's computer. 
image
Since they're not causing any issues I'm guessing that they're not being used so you might want to get rid of them.


Okay, now that that's done with, **Stuff related to PBC Layout/Design here**

Layout and routing seems pretty good. Looks super cool in my opinion. Just a few things I noticed: 

- Would it be possible to get rid of this fork in between J2 and J4 and just route all three traces directly from the pad?
image

- There's a few kinks near C6 and R4 that could probably be straightened out.
image

- Avoid right-angles when possible. I'm sure that most of these can be replaced with acute angles instead. This particular example is found near C2
image

- Some more right angles near the bottom-right of the board. The top-left one would be pretty tricky to re-route so you might be better off keeping that as is.
image

- More right-angles for SW1
image

- I noticed that you don't have a copper pour for the top of the board. Perhaps you could make one for power?

- There seems to be quite a bit of empty space on both the top and bottom of the board. It'll be difficult now that you've already done routing, but it might be nice to spread out the parts a bit more. Definitely would make it easier when soldering.


_Observations, not review comments:_ 
- There's a lot of useless `cache`, `bak`, and (potentially) `rescue`  files in the project directory that shouldn't be pushed to the repo, which led me to realize that the `.gitignore` for the repo isn't configured to handle KiCAD stuff. Just something to point out, you don't really have to do anything about it. Someone should setup the .gitignore unless there's a reason as to why it's not.

- We should probably set up all the Waterloo Rocketry logo footprints to be in a folder in `lib`, like how it is in canhw, to make it easier for projects to use them.

I'll probably make Github issues for these.

**Comment by zx100x100** [comment]
> Hello PCB review folks. Let me know about:
> 
> * Whether we should switch to a 4-layer design. If so, what sorts of signals would go on each of the 4 layers?
> * How I can improve the placement/routing on the current design.
> 
> Thanks.

I Think it would be cool to make it a 4 layer board. 
The standard layer stack-up for a 4 layer board is as follows:
Layer 1: Top signal layer
Layer 2: GND Plane
Layer 3: PWR Plane
Layer 4: Bottom signal layer

Here is an EEV blog video comparing 2 and 4 layer boards:
https://www.eevblog.com/2019/02/13/eevblog-1176-2-layer-vs-4-layer-pcb-emc-tested/

**Comment by ZTeper** [comment]
@zach Where is the "I2C valve" board? Can you please give an example of what you mean by switch numbering?

**Comment by ZTeper** [comment]
Should we add Test Points to the PCB? Like +12V, +10V, +5V, GND points?

**Comment by ZTeper** [comment]
Thanks Chamath. With respect to the SCL and SDA lines, I spaced them out deliberately to minimize cross-talk interference. Let me know if you think the spacing is unnecessary or if the lines should be closer together. Thanks for the helpful feedback :)

**Comment by QuantumManiac** [comment]
> Thanks Chamath. With respect to the SCL and SDA lines, I spaced them out deliberately to minimize cross-talk interference. Let me know if you think the spacing is unnecessary or if the lines should be closer together. Thanks for the helpful feedback :)

Ah yes, that's a good point. In that case, I think that you can leave a decent gap between the two lines while still removing a lot of the bends. I'm not too familiar with how cross-talk would work between the `SCL` and `SDA` lines, but I'd imagine that a minimum clearance of ~40 mils, as found near the mounting hole, is acceptable. Maybe something similar to this might work better?
image

To be honest, it's probably not that big of a big deal. I'm just a sucker for clean looks and all that.

**Comment by lwbantoto** [comment]
**Schematic Notes**
image

- Use a PTC resettable fuse. Add the part number of the fuse in the schematic
- Ceramic capacitors are fine for LDOs. Make sure to specify the rated voltage of the caps on the schematic so we can see if they're properly derated.
- Add a test point for 12V and 10V. 
- Make a note of how much expected current will be drawn from the LDO @ 10V

image
- Add fuses and a small decoupling capacitor (0.1uF) wherever power leaves the board

image
- Missing LED part number
- Missing I2C pullup resistors

image
- Add RC debounce circuit for switches. 10ms debounce time should be sufficient

image
- Add a fuse and decoupling capacitor where 10V leaves the board
- What value is R2? Why isn't it on the schematic?

**General**
- Add test points for important signals. Make sure to have sufficient ground test points as well

**Comment by zx100x100** [comment]
I agree with a many of these comments, although I do have thoughts on some of them:

The dip switches are steady state, never to be changed in operation as they select the I2C address, debouching is therefore unnecessary and is just more parts and more time to assemble.

R2 doesn't have a value as it is variable depending on the desired gain (note the text beside it that gives the gain equation)

F1 is supposed to already be a PTC, but yes, it should be noted as such, and the desired trip value should be added.

I2C pull ups will be added externally, you shouldn't add pull ups to every device on the bus.

I don't mind the LED not having a part number, there is no need to specify, any 1206 part is fine.

bypass caps on the output isn't a bad idea, although these connect to a few meters of cabling, I doubt the bypass caps would do much more than what the bulk bypass cap is already doing. 

Fuses seem unnecessary on every output and would add extra cost and assembly labor, not to mention another part to debug.

**Review by JaredWatson — COMMENTED** [review]
Looks good! I just have a few small comments at this stage that should or could be addressed:

- Power routing! It should be as small and fat as possible. I suggest increasing the GND and VCC power lines to slightly larger than 8 mils (something like 12 mils is what we have used on the team historically). Theres a couple funny wires that seem longer to me than they should be (see below)
image

- And this leads to another point (yet slightly less significant to us but I thought it should be mentioned regardless) that loops will lead to creating small amounts of inductance on your circuit, like the trace below
image

- That same SDA loop is daisy-chained through J7 which is fine if the function of the PIC depends on that jumper being connected. I however think it _should_ not be (again this depends if both I2C jumpers need to be intact for it to work)

- STR1 is going through the back of the PIC, we discussed on slack and agreed it should probably be moved
image

- Along the same vein, STR2 looks a _little_ close to J3, giving it some room to breathe would probably make life easier (unless it messes up the routing too much).
image

Other than that, everything looks solder-able, the silkscreen is readable and I don't spot any daisy chains aside the one mentioned so looks good. If those loops aren't critical (which I suspect they aren't) the power lines are the only thing I'd really like to see change (unless someone else disagrees) and I think it'll be good! Feel free to leave gerbers with your next commit (whether you make any of these changes or not).

**Review by zx100x100 — CHANGES_REQUESTED** [review]
getting really close, just a couple more points:
1. minor aesthetic thing, but it is clearer if all of the reference designators are in the same direction, versus right now a bunch of them point in different directions.

2. you increased the track width on the 12V line, but not the net that leads into the regulator from the fuse, as well as you should increase the width of the 10V line and via leading to the 10V plane.
image

3. We have full power planes, let use them! I noticed you run a bunch of 10V and GND traces. since we have complete planes for these they should all just be a super short trace leading to a via. the only parts this isn't the case for are bypass caps which should have the shortest possible path to the chip they supply. you are also daisy chained through C2 and pretty much daisy chained through C5
image
Same issue with daisy chaining and to many traces with ground plane
image

I also just realized it is possible to put 10V into the PIC, we need to fix this, see discussion in #DAQ

**Review by zx100x100 — COMMENTED** [review]
looks alright to me. probably still a few places you could tidy up the routing, and the reference designators point in different directions and sometimes have inconsistent spacing but those aren't big deals.
My only concern is what the zener voltage at 16mA will be > than 5.3V, in which case we will exceed the maximum voltage rating on the pic, see slack for discussion.

**Comment by zx100x100** [comment]
Please add I2C to the name, or make it clear this board is different from regular pancake in some way.

**Comment by QuantumManiac** [comment]
Looking good! Just a few random things to point out while I was taking a look at the project libraries:

image
It seems that there's some project-specific symbol library that is pathed to Alex's computer. I don't think it's causing issues but do get rid of it.

image
Same with these project-specific footprint libraries

Other than that, take care of the reviews from the others and do a bit more route tidying. Looks very close to completion!

**Comment by jacobdeery** [comment]
Can you please remove the space in the filepath (`I2C Pancake` --> `I2C_Pancake` or something similar)?

**Review by zx100x100 — COMMENTED** [review]
Here is my review of the updated design:

1. the schematic symbol libraries aren't loading correctly for me, not sure if this is an issue specific to my machine, but if it is an issue for others as well then we need to fix that.

2. I think your math is wrong for the RC filter, I have double checked my work and I get a cut off of 1kHz, not 6.7kHz. I'm pretty sure you forgot the 2pi term in your equation / used the equation for rad/sec instead of Hz.
That being said, I think 1 kHz is a good cut off frequency. your note says that the pic has a maximum sample rate of 6kHz, to avoid aliasing we therefore need to cut off anything above 3kHs. so 1kHz gives us some wiggle room, and you have selected values we already have.
- only action item here is to update the schematic note.

3. you are daisychaining the 5V rail through one of the connectors:
image

4. I find naming the main 5v net VDD kinda confusing, as well as while it's probably fine it seems weird to have a few pull up resistors before the fuse, and then everything else after.

Overall looks really good, just need to fix that one trace and we should be good!

**Comment by AidanHa** [comment]
Seems like  my schematic liubrary didn't load properly as well.  Board looks good to me once the above comments just addressed ^^

**Review by zx100x100 — APPROVED** [review]
One way or another this board has been ordered, as such this should be merged.

**Review by QuantumManiac — APPROVED** [review]
Approved since things have already been ordered. We can put some issues up if anything needs to be changed.

**Review by AidanHa — APPROVED** [review]

**Comment by AidanHa** [comment]
change requested, but I assume its outdated. I'm down to merge

**Comment by ZTeper** [comment]
Approved. Let's merge.

**Comment by ZTeper** [comment]
@JaredWatson can we dismiss your old requested change?

**Review by JaredWatson — APPROVED** [review]
Looks like my comments were addressed in 98e0d0dcaca66a9584acdc5a5413f22c361273e4. LGTM

**Comment by jacobdeery** [comment]
which one of y'all wants to actually hit the merge button?

**Pull request merged**
