### PR TITLE
Spidey Sense v2 board schematic

### PR DESCRIPTION
**Pull request by aprilove**
Would also like to know if connecting all the gnds on this board will be bad. Any advice regarding board design will also help.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/15)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Great start! Mostly minor readability comments.
1. Please edit the symbols so that the pin names are inside the outlines for the ICs and the part numbers are outside, significantly helps with readability. Generally try to keep text from overlapping other things, such as the U2 label.
2. I think it will probably be more efficient to have multiple copies of this circuit per board. I think you would be able to have one LT1025 and then multiple (say 4?) LTC1049s. Also best to have separate screw terminals for power, thermocouples and output.
3. We want to be able to use the full K-type range (-200 to +1350 C) so you'll need to fiddle with the gain to get a reasonable output voltage (try to scale it to 4V). It's good practice to leave your calculations as text in the schematic. You also don't need to stick with the layout in the datasheet, eg you could make it more clear that those resistors are a voltage divider.
4. Ambient temperatures may be < 0 C (we test in the winter) so I think you'll need to connect V0 on the LT1025 (I'm basing this on the note on the front page of the datasheet, please correct me if I'm mistaken). If it should be disconnected, please mark that with a 'no connection flag' in kicad.
5. You might have to show the other pins on the LT1025 so that kicad plays nice when designing the PCB, I'm not certain about that though. In terms of this being a useful part in our library (for other thermocouple types) might be a good idea to anyways.
6. Please orient / position the screw terminals such that the 'screw' is on the left for inputs and the right for outputs, and outputs are on the right side of the schematic.
7. You should wire power / GND on the screw terminals to the appropriate power symbol rather than using net labels. See the 'place power port' tool for lots of pre-defined voltages and appropriate power symbols.
8. How were those capacitor sizes chosen in the datasheet? We should double check that they work for our needs and add the calculations to the datasheet.

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
I think the above review pretty much covered everything, can't find anything else to bring up.

**Comment by aprilove** [comment]
In regards to the first comment, how should I approach point 2, should I just hooking up multiple screw terminals to the LT1025 and have multiple amplifier circuits? Secondly, I'm not too sure on how to add a full scale trim resistor to reflect the gain calculated. 

More importantly, I added another thermocouple design (Spidey_Sense_v2.1) which is significantly cheaper (though it only offers the chip in SM). It used the AD8495 which provided more easy to read documentation and was in general more understandable (as it is a thermocouple amplifier with a cold junction compensator built in it). On the other hand, it does not specify what the error is outside of its measurement temperature range (-25°C to 400°C) and only says error will be nonlinear. Any comments about it would be helpful!

**Comment by BluCodeGH** [comment]
V2:
2, Yep multiple input screw terminals and amplifier circuits exactly.
3. The gain is set by the resistor divider made of up R2 and R3. I think in this case the way to think about the circuit is that the op amp sets its output voltage such that the thermocouple voltage is equal to the output divided by 255.
4. If you need a -5V source you should put the regulator to provide that on the board rather than using a screw terminal. Also looks like the input screw terminal is still labeled -15V but the rest of the circuit uses -5V.
6. Looks like you've got the screw terminal direction flipped, the (at least rocketry) convention is for the wires to go to the right for inputs.

V2.1:
9. The REF pin only sinks a few uA of current, I don't think you need an op amp there.
10. I was originally looking at this chip but the problem is that it's out of stock everywhere. LMK if you've found a supplier but otherwise I think we might be stuck with V2.

**Comment by aprilove** [comment]
Updates to names: changed V2 to V2.0.

V2.0:
Not sure whether there exists a device that takes in a positive supply and outputs a negative supply. From my understanding, I used a negative voltage regulator as suggested.

V2.1:
The op amp is for a cleaner supply (recommended in the datasheet, not sure what a regulator was not suggested).

V2.2:
New circuit that uses the LTC2997 and LTC6078 that should be able to measure from -200°C to 1300°C (with ~ -0.5°C error for most of the spectrum). Not sure if we should continue with the 2.1 or 2.2 circuit, would like a recommendation on what to do next. 

I'm also not sure about notation, to notate 1.8V power symbol in kicad should I use the +1V8 power symbol.

**Comment by aprilove** [comment]
Update on V2.0
Switched the negative voltage regulator to a DC/DC switching regulator as per suggested.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
2.0
11. According to https://ez.analog.com/temperature_sensors/f/q-a/114933/using-the-lt1025-to-compensate-multiple-thermocouples, there isn't a limit on the number of thermocouples. I think 4 sounds like a pretty good number for this board though.
12. All the examples for the LT1025 I see connect R- to GND not -5V?
13. For the thermocouple screw terminals, it would be best to have 4 separate 2-pin screw terminals, each with its own K+ and K- (well the K-s would all be connected, but still). If you put the amplifier circuit in its own sheet you can duplicate references to the same sheet and directly connect each K+ to its own amplifier.
14. Since you're creating and using -5V on the same board you shouldn't need to jumper it with a screw terminal lol. Good to add a test point on the -5V line but that should be all you need.
15. Looks like you're missing the output capacitor on the -5V regulator.
16. Why are R2 and R4 separate resistors? If you're looking at the front page of the LT1025 datasheet, R2 is a variable resistor that lets you trim the gain of the op-amp to better match the range of your DAQ device. We don't need that level of precision, best to stick with an amplification that gets us to roughly where we want. By my calculation your current gain of 213 puts us at 12V when reading the max possible of a K-type, 1350 C (41/1000000 * (255+1.2)/1.2 * 1350).
17. I'm also concerned about the output range of the LT1001 when we're powering it with only +-5V. We might have to scale the output voltage to 0-1V (the DAQ box has different voltage ranges we can set it to: 0.2V, 1V, 5V and 10V).
18. Looks like your note under the op amp about R4 > 250k is out of date?

2.2
Yep +1V8 is correct.
19. The 1.8V line of the LTC2997 is an output, not an input.
This design doesn't seem like a great option, the LTC2997 obviously wasn't designed to act as a cold junction compensator where the LT1025 definitely was. I also don't get why it recommends the LTC6078 when you only need one of its two op-amps, it seems like sticking with a single op-amp chip that's more explicitely designed for this would be better. I get that this saves the -5V supply but that works out to just being a few components, I think the simplicity/understandability of V2.0 makes it more likely to work. Awesome work exploring our options though!

**Comment by aprilove** [comment]
2.0
Addressing the comments,
12. Fixed, not sure what happened here
13. Fixed, each Vout screw terminal is also in the amplifier sheet (I'm not sure if there is some sort of convention on where to put it)
15. Added
16. Fixed, gain calculations in the Amplifier sheet
17. Changed the output voltage to ~0.2V to 1V
18. Fixed

2.2
I will stop working on this one.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks good! Just a few tweaks.
13. The Vout terminals should all be one 4-pin on the main sheet. When they are together then they map to a single 4-position screw terminal on the pcb rather than four 1-position screw terminals.
14. There is a part called 'test point' you can use rather than a screw terminal, it becomes a bit of exposed copper on the board so we don't need to worry about attaching anything.
17. Not sure what your V_H / V_L calculation is, by the same calculation as the maximum we can compute the minimum. (41uV/C)(18.1)(-200 C) = -0.148 V. That's acceptable since our DAQ system can measure negative voltages.
19. Right now all of your K+s are connected, since everything with a K+ label is connected. Instead, directly wire the 4 screw terminals to the amplifier sheets.
20. Try to avoid using global labels (use local labels, right above it in the toolbar). Since K- isn't used on other sheets, it should be local.
21. GND, +5 and -5V are all global, you don't need to pass them into the amplifier sheet.

**Comment by aprilove** [comment]
13. Fixed
14. Added a test point 
17. I'm not too sure the calculations made for V_L are correct.
The gain is given in the datasheet is G = (SF)(T<sub>H</sub> - T<sub>L</sub>)/(V<sub>H</sub> - V<sub>L</sub>)
Since for a thermocouple, V = (41uV/C)(G)(T) and substituting into G,
G = (SF)(T<sub>H</sub> - T<sub>L</sub>)/[(41uV/C)(G)(T<sub>H</sub> - T<sub>L</sub>)]
Which arrises an interesting situation where,
G<sup>2</sup> = SF/(41uV/C)
19. Changed
20. Fixed
21. Removed the global labels

**Review by BluCodeGH — APPROVED** [review]
Great, feel free to proceed with layout!
17. That equation looks to be about doing some sort of calibration at the amplifier level, we can handle everything in software so probably easier to keep it as a simple linear amplifier. The reason things work out weirdly is that you set the scaling factor to 10mv/C but really that is determined by the 18:1 gain (works out to be about 0.74mv/C).
22. If you have some free time you could tidy up this schematic a bit. It's nice to keep things symmetrical / consistent (eg the two GNDs on U1), and I personally like two 'grid dots' of wire on either side of a corner / junction to space things out nicely, such as
image

**Review by QuantumManiac — APPROVED** [review]
Typo on the v2.0 schematic:
image
"Calculating"


> I personally like two 'grid dots' of wire on either side of a corner / junction to space things out nicely,

Agreed with Jack, doing so would make things a bit less cramped. The distance between grid dots changes depending on zoom level, but in the screenshot provided it seems that 2 grid dots would be 0.050 mils.

Otherwise, looks good to proceed to layout!

**Review by rdakhil — APPROVED** [review]

**Comment by aprilove** [comment]
PCB has been routed
1. I will need to add a couple silkscreen components as certain components require specific parts
2. I will also edit the footprint to better show the orientation of each chip as the footprints from mouser are not very good (the ones on snapeda are ok but are not consistent)

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Great start!
1. It's probably best to keep J3, J4, J5 and J6 together, so it's easy to tell during tests what should get plugged into where. You could do something like having them on one side of the board and J1/J2 on the opposite. Also a good idea to add silkscreen text saying what each screw terminal pin does.
2. You have lots of space, please use a rectangular hole pattern. Even better if you can keep the distances between holes to nice round numbers (use the measure tool to verify).
3. You're currently missing front and back filled zones, for a board like this I think you'd be best off with GND fills on the front and back (meaning you don't need to have any GND traces).
4. In the interest of this board being debug-able, I think it would be best to figure out a compact layout for the 'amplifier' schematic and then copy that same layout 4 times. Keeping things consistent makes it much easier to know where to look when debugging. Also speeds up assembly.
5. Speaking of assembly, I'd suggest trying to only have components on the front of the board. Doing so makes assembly a lot easier, and also helps out with debugging (everything is on the same side so you can probe without flipping the board),

**Comment by aprilove** [comment]
1. Changed so that J1 and J2 are together while J3,J4,J5,J6 are on the other side of the board. Also added silkscreen for each terminal
2. Changed to a rectangular hole pattern
3. Added GND fill zones
4. Each 'amplifier' schematic is the same, though some of the trace paths do differ
5. Moved everything to front of board

Additional Comments:
- Changed mounting holes to the ones found in the I2C pancake
- Added silkscreen on C4 about being low ESR

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looking much better!
1. It's clearer to keep the outputs in the same order as the inputs rather than swapping the order like you've done here.
2. No harm in making the connector pinout silkscreens bigger where possible, especially K- and K+.
3. If you have GND fills on the top and bottom then you shouldn't have any GND traces. If your traces are dividing the GND fills into disconnected zones feel free to add vias to bridge them, but no need to have traces connecting to those vias when the fill will do that for you. It's easy to spot GND traces using kicad's "highlight nets" feature, hover over something that is connected to GND and press ` (backtick).
4. There's a lonely V3 silkscreen off above the board.
5. You've got a handful of instances of daisy-chaining, should be an easy fix.
I've written a bit more about some of these comments on the [PCB reviewing tips](https://uwaterloo.atlassian.net/wiki/spaces/ROCKETRY/pages/42646667708/PCBs) documentation page, maybe give it a read through.

**Comment by aprilove** [comment]
1. Fixed!
2. Made K- and K+ slightly bigger, the other silkscreens seem too cramped when increased in size
3. Changed!
4. Fixed!
5. Did some rerouting to remove all the daisy-chaining that I was able to find

**Review by BluCodeGH — APPROVED** [review]
LGTM! A few cleanup tasks:
1. Please remove the other spidey sense folders and rename the spidey_sense_v2.0 folder and files back to spidey_sense (git will track the old version for us).
2. Remove the amplified "kicad project", it is a subsheet and not a standalone project. (.kicad_prl and .kicad_pro files)
3. Remove the old kicad 5 .pro and .sch files (amplifier and spidey sense).
4. Add the backups folder to the .gitignore (add the line `/*-backups`) and stop tracking the currently tracked backups (google is a good reasource for how to do this, if its done correctly then no backup files should show on github)

We should also wait for a few more :eyes: before merging.

**Review by QuantumManiac — APPROVED** [review]
LGTM.

The `Spidey_Sensev2` and `spidey_sense_v2.2` folders still seem to be around, although with only a single `fp-info-cache` file within each. Should be good to remove.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Why did you add I2C_Pancake to the gitignore? Also no need for a spidey-sense-specific gitignore, since our other boards will eventually need to use kicad 6 too.

Last thing to do before merging this, please add all of the components this board will require (export the BOM from tools->generate BOM->bom_html_with_advanced_grouping) to the [master electrical orders spreadsheet](https://docs.google.com/spreadsheets/d/1BueiN9HmC8HtrSg3OIwg5nm5VYwdf4eYnYHdHctQ7GE/edit?usp=sharing), make sure to find digikey part numbers that are in stock.

**Comment by aprilove** [comment]
Removed both gitignore.

bom_html_with_advanced_grouping does not exist in KiCAD 6. Used bom_csv_grouped_by_value_with_fp and added the parts to the master electrical orders spreadsheet. LT1001 seems to have ran out of stock on digikey so I added the part from mouser.

`spidey_sensev2` and other variants seem to be gone on my side and the branch doesn't seem to be showing them on GH. If someone could double check this on their side.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Please don't delete the root .gitignore, I meant you should merge the spidey-sense one with the root one since other non-spidey-sense boards will benefit from having backups ignored.

Github is the source of truth for what's been ignored, I think Chamath just had some of his own files sticking around.

**Comment by aprilove** [comment]
Added back the root gitignore. The gitignore only ignores the files in the spidey_sense backup, should I change this to all zips?

**Comment by BluCodeGH** [comment]
You should leave the root gitignore untouched in this PR except for adding the line `*-backups/`. The rest of the lines there are important and should stay.

**Comment by aprilove** [comment]
My bad, I didn't realize I had wiped the root gitignore. I have now added the line `*-backups/`.

**Comment by ZTeper** [comment]
Please add vias here to eliminate ground loops: 
image

**Comment by ZTeper** [comment]
Please also add a pdf of the schematic

**Review by ZTeper — CHANGES_REQUESTED** [review]
Please add a pdf and put in vias as suggested

**Comment by aprilove** [comment]
Changed.
- Added vias to avoid GND loop
- Added pdfs

**Review by BluCodeGH — APPROVED** [review]

**Review by rdakhil — APPROVED** [review]

**Comment by LanaTomlin** [comment]
heyaaaaa 
image
this bad boi is bound to be prettttttyy noisy, might wanna add some more decoupling caps, & mayyybe a filter on the output 
image
that cap on the non-inverting input is gonna slow down your response & potentially create oscilations (well it definitely would if it were on the inverting input, but bc its on the non inverting im not sure) 
also are you aware youve got a filter in here? its prob good to have, but have you done any bandwidth calcs? you have decent bandwidth, but the filter is gonna cut that off and you might end up losing gain 
oh yeah,,, youreeee definitely gonna want more filtering on your power supplies, this is gonna be sensitive to noise. I'd also shove a diode on te end of the filter so the capacitance of the filter is seperated from the power on the op amp and it doesnt fuck with your speed too much
where did this design come from? 


oh boy i reaaaaallly shouldve reveiwed this earlier

the pcb looks great tho!

**Review by LanaTomlin — DISMISSED** [review]
hi i have....concerns im sorry

**Review by ZTeper — APPROVED** [review]

**Comment by BluCodeGH** [comment]
Just talked with Lana at the review beer, we realized that most of the things she pointed out aren't actually issues (we're dealing with low frequencies and a charge pump). That being said, you should reduce the value of C5 to 0.1uF to reduce its noise and link the LT1025 datasheet above the amplifier circuit so its clear what's going on.

**Comment by aprilove** [comment]
Changed the value of c5 (will change the master spreadsheet too) and added a link to the 1025 datasheet.

**Pull request merged**
