### PR TITLE
Thermocouple board

### PR DESCRIPTION
**Pull request by DomenicHampson**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/23)

### CODE REVIEW

**Comment by Joe-Joe-Joe-Joe** [comment]
I have never seen the old board design, but everything here more or less checks out. My question would be, have we actually figured out what went wrong with the thermocouples at SF? Are is this a hail mary to hopefully fix whatever the root cause may be?

**Comment by DomenicHampson** [comment]
There are several theories as to what went wrong I will forward you the chat in slack. This board is using the same thermocouple to digital converter and filtering as FYDP which had great performance so we expect similar results.

**Comment by Artem-Sotnikov** [comment]
A few comments:

1. The thermocouple chip operates at a 3v3 logic level on it's spi lines. If the intention to use a 3.3V PIC? I don't think the regular pic can be configured to run it's SPI at 3v3. It might be easier to just use a level shifter. For that, either design a discrete level shifter or use a monolithic shifter chip like the FYDP schematic. 
2. There are no test points anywhere. At an absolute minimum you should put them on the 5V, GND, 3v3, SPI and CAN lines. CS lines may also be nice. Depending on the level shifting strategy, TPs upstream and downstream may help with debugging. 
3. I would recommend external pullups on the SPI lines. Yes it can be done on the PIC configuration but an external pullup is more foolproof and can be DNPed later if you all feel like it. This is a ground board so there isn't a giga space requirement here.
4. Why the change of capacitor values in the acquisition circuit? They have conventionally been 0.1 uF elsewhere. I would recommend keeping it this way unless you a good reason to do so.
5. The 3v3 LDO doesn't appear to have the correct capacitor values. I would suggest 4.7 uF on the input and 10 uF on the output; In general, page 31/38 of the datasheet should be examined further since it goes in depth with regard to capacitor selection.

image


6. This might be getting a little nitpicky but a TVS diode on the 5V line won't hurt. 
7. A few more stylistic changes could be made if the designers feel like it considering that this is a ground board. Always-on LEDs for the power lines, and perhaps in a few other spots could help those working with the board assess its health at a glance. This may be especially nice if you are planning on keeping this guy outside for prolonged periods of time.

**Comment by Artem-Sotnikov** [comment]
Actually I would slap 22 uF on the output, they are still widely available in the 0805 package

https://www.digikey.ca/en/products/detail/murata-electronics/GRT21BR61E226ME13L/5416811

**Comment by Artem-Sotnikov** [comment]
I looked over the schematic and there are still a few things missing. 
1. It's still a little light on the test points imo
2. A major outstanding issue is the fact that the chip select lines are still 5v (they need to be level-shifted like the rest of the SPI lines) and they should also be pulled up with resistors.
3. The t-/t+ bypass cap is still labeled as 0.01 uF (did further analysis reveal some reason to keep it so?)

**Comment by DomenicHampson** [comment]
Sounds good! I swear I switched the cap value that's weird. Will fix and design pcb tonight

**Review by JasonBrave — CHANGES_REQUESTED** [review]
1. I don't think the LEDs are necessary, we are just replace those with test points
2. Chip-select(CS) need level shifting too

**Comment by DomenicHampson** [comment]
Put this together very quick because I have to do something for a couple hours. If you leave a review dw about silkscreen labels or the rough corner I'll fix that when I get back

**Review by JasonBrave — CHANGES_REQUESTED** [review]
1. Lmao all screw terminals are in wrong direction

**Comment by Artem-Sotnikov** [comment]
Looked over the routing, have a few comments.

1. The CAN lines slice the ground plane almost completely in half. Definitely needs some stitching. 
2. Why are the test points so cringe? Why not use the keystone ones? This design is certainly not hurting for space in the top right of the board.
3. If we're planning to use the second CAN connector for daisy-chaining (a good idea), the 5V trace should definitely get beefed up.

image

**Review by JasonBrave — APPROVED** [review]

**Pull request merged**
