### PR TITLE
Briefcase power board

### PR DESCRIPTION
**Pull request by BluCodeGH**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/13)

### CODE REVIEW

**Review by LanaTomlin — COMMENTED** [review]
ALRIGHTY: 
So this might be half of a review because I am going to be called away at any moment but something's better than nothing, I suppose.

Switching regulator:
1. Please source/put down the part number for the inductor. The same value of inductor from two different manufacturers can have vastly different characteristics.
2. Is TP8 going to interfere with the layout of the regulator?
3. 19.2V for lockout and start voltage at 19.3V sounds like a very tight tolerance - you could swtich between those two just with imprecise resistors, What's the value of your input voltage?
4. 1.82k is a very specific number, can you find a resistor that specific?
5. Why in gods name do you need an 8.2nF capacitor? That's very specific for a soft-start cap, maybe 10nf would still give you basically the 2ms you want?
6. High switching frequency, nice. Usually the higher the better, is there a reason you chose 1.7 Mhz and not 2.2Mhz?
7. What's the value of C1?
8. Might be a good idea to double check the ESR n your output caps to make sure you're not too high. but putting two in parallel lowers ESR so kudos for that
9. Might be a good idea to put the est. output current and max. output current on the schematic
10. also quiescent current and power in
11. finally, if you haven't checked thermals, 
image
From the looks of this boi, you should be good, but it might be a decent idea to load this up in LTSpice, and check how much heat this is gonna generate if you're got a a low load. 

LDO REVIEW COMING SOON!!
also make sure your diode is in stock

**Comment by BluCodeGH** [comment]
1. Done (also realized that lower currents make webench use a bigger inductor so used a 2A max instead of 3A)
2. Nope, on the recommended layout that net is a big fill
3. The way it works is that it turns on above 19.3 and off below 19.2, the goal is to protect lipos so there's no resistor divider trying to hit within that range or anything. Nominal input is 24V on DC power but could range from 19.2 - 25.2 with lipos.
4. 18.2 is a standard 1% resistor multiple.
5. Yeah 10nF works fine, I don't see a reason to be picky about soft start time.
6. 1.7Mhz roughly lines up with a PSRR peak of the LDO
7. Webench just recommends the 10uF input capacitor so I have C1 as optional if we need to add a second.
8. Added a note with what webench asks for
9. Done
10. Done
11. Yeah we should probably be in that 80-85% efficiency range. Even if it's only 60% efficient at those low currents we're not dissipating a lot of power.
12. Yes diode is in stock (but only 137 of them), luckily webench gives us tons of alternatives if it goes out of stock.

**Review by zx100x100 — COMMENTED** [review]
Looks good to me. my only note is I think it would be good to add resitor tolerances since I'm guessing some of these should be better than +/- 5%, but I think you are good to go ahead with layout.

**Review by QuantumManiac — COMMENTED** [review]
:lgtm:, should be fine to proceed once above comments are addressed

**Comment by BluCodeGH** [comment]
Alright first pass at routing complete, I really have no idea what I'm doing when it comes to grounding things properly to avoid noise so reviews / knowledge would be greatly appreciated!

**Comment by rdakhil** [comment]
Looks great! Just a few comments:

1. Nitpick but the datasheet link is missing for the buck converter on the schematic
2. I would recommend moving L1 a little closer to the SW pin as it's a bit far which could cause some noise
3. C2 should be as close to VIN on the buck converter as possible
4. Not sure if there is a reason for it, but C9 is daisy chained to C12 and has no other connection to GND
image
5. Depending on how much current you could be running at, you might want to add a fuse to your battery connector and make any traces connected to +BATT thicker (eg. R3, R7) or alternatively you could use a +BATT polygon

**Comment by BluCodeGH** [comment]
1. Done
2. I couldn't get the layout to work out nicely with L1 closer, do you think it will be a significant issue? The reference design from webench has it fairly far away.
3. Done
4. This is a kelvin sense connection, it lets the LDO get an accurate voltage reading irregardless of high currents flowing through that capacitor.
5. We're only looking at 1A max so the trace widths should be plenty. Also R3 and R7 are just for sensing so will only have a few milliamps at most.

**Comment by BluCodeGH** [comment]
I really want to get this ordered in the next couple days so DAQ can be ready for cold flows before I need to leave Waterloo, please review if you have some time!

**Review by rdakhil — APPROVED** [review]
For this board it should be fine not having L1 closer to the SW pin (unless you are particularly concerned about minimizing parasitic inductance). Looks good to me!

**Review by LanaTomlin — APPROVED** [review]
1. Are you sure you want to use a screw terminal
	a. i have a love hate relationship relationship with screw terminals
	sometimes they're great, sometimes they're awful, lipos usuallly have connectors on them
	could you use the connector instead? Might save you some headaches/potential shorts.
	No harm in having both, either.

2. having the set resistors outside of the sheet is confusing, maybe wanna explain what you're setting there
3. why 0603, the team typ. uses 0805? i appreciate that little notice tho 10/10
4. fuck im getting carsick
5. i reviewed these LDOS before so im not gonna go in depth, looks good, why are you using such a small resistor tho??
6. these are fancy LDOS i wish i had wifi so could look at the app note
7. DAMN YOU'RE USING VIOC, THAT'S REALLY FANCY, i was so curious about that the first time i read about it
it's so cool
8. ON THAT this is a pretty damn complicated power supply system (which i rate 10/10 for VIOC alone) 
you migtttHTTT want a back-up just connection just in case it doesn't work, espc. considering you're
yeeting to montreal 
9. love your fat caps
10. big fan of fat capps
11. yummy fat caps
11. it took me wayyyy too long to figure out that OPT meant optional, that's smart, yes 
12. did you check if your resitors exist/dont' cost an arm and a leg
13. is 1.7Mhz the highest frequecny? highest frequency is usally better, i dont remember i feel like i checked this last time
14. Do you kwno what kind of inductor you're using? pls put inductor MPN on schematic
15. OOOOOOOOOO SUPER FAT CAPS fuckn' love it, and 10/10 for voltage max, you want that shit
on electorlytes
don't want one of those to blow up and scare your roomate half to death....noooo
16. i am suprisingly, not super carsick
17. you put an amperage max on one of your terminals, do the rest of 'em have maximum ratings as well?

PCB:
1. some of your traes are really tiny. 
FUCK I CANT PUT IMAGES IN HERE ugh okay +out on R12 is really tiny
as the late and great Jared Watson once said "smallest trace size of smallest pad" that is not a direct quote
2. love 'em gnd vias
3. OUT GND nad C8 and R2 are pretty close and i dont think they quite need to be
4. same for setfs and outgnd, you usually want a bit more space for through hole componenents
5. WHY IS IT CALLED SILENCE
yeah that's it this looks beatiful except for those tiny ass traces why are they so tiny 

OKAY ITS BEEN FUN
im approving this anyways bc a. im beign super fucking nitpicky b. you have good reason to want this in

**Comment by BluCodeGH** [comment]
1. Don't worry these are big fat screw terminals, also this board is not going to be directly connected to a battery it will go through the power distribution of the briefcase first.
2. Done
3. Don't worry I used 0805 footprints, note was just wrong
5. Datasheet said to /shrug, added a note
8. Backup is the current pancake boards
13. Wilco.
14. 1.7Mhz has the highest PSRR on the LDO
15. It's there (under the datasheet field).
18. That's the amperage rating of the entire board not those terminals.

1. All the tiny traces are just carrying signals, don't worry I made the actual power traces big. R12 is part of the feedback from the output voltage to the LDO.
3. But fixing this would be a lot of work and messes up my symmetry :frowning_face: 
4. Moved a bit further.
5. Since it's a super low noise power supply.

**Comment by BluCodeGH** [comment]
Hardware has been ordered, merging.

**Pull request merged**
