### PR TITLE
Inflight recording

### PR DESCRIPTION
**Pull request by chrissank**
This branch adds code and instructions on how to setup the inflight recording cameras (and, really, the cameras we will use on the pad / at static fires)

Currently the camera will:

1. Begin recording on power on
2. Save a copy locally (in the /home/autovid folder)
3. Stream the video over a Real Time Streaming Protocol connection (rtsp)

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/11)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
I've never written a systemd service, so I don't have anything useful to say about that file. Just a few documentation nitpicks from me.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-:-MbPE8iZEJaf3pXEexbV:b3t8kdp)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @chrissank and @ZTeper)

___
*[inflight_recording/autovid.sh, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPDyYC3avxm7OUoDMk:-MbPDyYC3avxm7OUoDMl:blfa7yy) ([raw file](https://github.com/waterloo-rocketry/daq/blob/ae1614ba3774932ba86e839f4f30d5c10733700d/inflight_recording/autovid.sh#L3)):*
> ```
> NOW=$(date +%Y%m%d%H%M%S)
> ```
Can you leave a comment with an example of what this format will look like?
___
*[inflight_recording/README.md, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPE5c_D-oT7elGtyVc:-MbPE5c_D-oT7elGtyVd:b-latdws) ([raw file](https://github.com/waterloo-rocketry/daq/blob/ae1614ba3774932ba86e839f4f30d5c10733700d/inflight_recording/README.md#L2)):*
> ```
> HOW SETUP
> ```
`HOW TO SETUP`
___
*[inflight_recording/README.md, line 25 at r2](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPDj9U0ruz6QYMTRap:-MbPDj9U0ruz6QYMTRaq:b-xpqrx9) ([raw file](https://github.com/waterloo-rocketry/daq/blob/ae1614ba3774932ba86e839f4f30d5c10733700d/inflight_recording/README.md#L25)):*
> ```
> 1. Run `sudo cp autovid.service /etc/systemd/system/`
> 1. Run `sudo systemctl daemon-reload`
> 1. Run `sudo systemctl enable autovid.service`
> ```
Can you add a `setup.sh` script that runs these three commands for convenience?
___
*[inflight_recording/README.md, line 41 at r2](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPDoP34XB-VDvNvzG6:-MbPDoP34XB-VDvNvzG7:bqv4euv) ([raw file](https://github.com/waterloo-rocketry/daq/blob/ae1614ba3774932ba86e839f4f30d5c10733700d/inflight_recording/README.md#L41)):*
> ```
> is be in
> ```
`is in` or `will be in`

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/11)* status: all files reviewed, 9 unresolved discussions (waiting on @chrissank and @ZTeper)

___
*[inflight_recording/autovid.service, line 3 at r3](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPtN4PD0W_o180eb4e:-MbPtN4PD0W_o180eb4f:b-el2901) ([raw file](https://github.com/waterloo-rocketry/daq/blob/fe0db1461142adfe4892414f3df14b3179d97579/inflight_recording/autovid.service#L3)):*
> ```
> [Unit]
> Description="automatically record video footage"
> After=local-fs.target
> ```

All of the unit files I've seen also include a line like `Wants=local-fs.target`. `local-fs` also seems a bit early for something that is trying to stream over the network, I'd suggest waiting for `network.target` if you're running into issues with it failing to start.
___
*[inflight_recording/autovid.service, line 14 at r3](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPu8MP4J5RZF-XLd2h:-MbPu8MP4J5RZF-XLd2i:bgygx3l) ([raw file](https://github.com/waterloo-rocketry/daq/blob/fe0db1461142adfe4892414f3df14b3179d97579/inflight_recording/autovid.service#L14)):*
> ```
> 
> [Install]
> WantedBy=sysinit.target
> ```

`sysinit` is again very early in the setup process, the most common target for things like this is simply `default.target` which is after all of the standard background services that this might depend on have started.
___
*[inflight_recording/autovid.sh, line 7 at r3](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPuhDcEZhhnECRZRpu:-MbPuhDcEZhhnECRZRpv:b-3zqgd6) ([raw file](https://github.com/waterloo-rocketry/daq/blob/fe0db1461142adfe4892414f3df14b3179d97579/inflight_recording/autovid.sh#L7)):*
> ```Shell
> VIDEO_FILE="/home/pi/autovid/video$NOW.h264"
> 
> raspivid -t 0 -fl -ih -l -o - | tee $VIDEO_FILE | cvlc -vvv stream:///dev/stdin --sout '#rtp{sdp=rtsp://:5000}' :demux=h264
> ```

Nit, it's good practice to wrap all `$VARIABLE`s in double quotes. You also probably don't need the `-vvv` here given that stdout isn't being logged (which you may want to do anyways, but still `-vvv` is likely unnecessary). Also a comment explaining what the programs making up this pipe all do would be good.
___
*[inflight_recording/README.md, line 35 at r3](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPvMPYC0xXJyy0-zUc:-MbPvMPZ7vpEL3-BCFAV:b-mktivb) ([raw file](https://github.com/waterloo-rocketry/daq/blob/fe0db1461142adfe4892414f3df14b3179d97579/inflight_recording/README.md#L35)):*
> ```Markdown
>     1. user: pi
>     1. password: raspberry
>     1. port: 22
> ```

FTP is classically on port 21, is 22 correct?
___
*[inflight_recording/README.md, line 36 at r3](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPvZls6D7xyQKVeGxW:-MbPvZls6D7xyQKVeGxX:bb8nbqj) ([raw file](https://github.com/waterloo-rocketry/daq/blob/fe0db1461142adfe4892414f3df14b3179d97579/inflight_recording/README.md#L36)):*
> ```Markdown
>     1. password: raspberry
>     1. port: 22
> 1. Navigate to the `/autovid` folder
> ```

Nit, either `~/autovid` or just `autovid`.

**Review by chrissank — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/11)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @BluCodeGH, @jacobdeery, and @ZTeper)

___
*[inflight_recording/autovid.service, line 3 at r3](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPtN4PD0W_o180eb4e:-MbTV5i6EoHtM_Rr1pRU:b-896fix) ([raw file](https://github.com/waterloo-rocketry/daq/blob/fe0db1461142adfe4892414f3df14b3179d97579/inflight_recording/autovid.service#L3)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

All of the unit files I've seen also include a line like `Wants=local-fs.target`. `local-fs` also seems a bit early for something that is trying to stream over the network, I'd suggest waiting for `network.target` if you're running into issues with it failing to start.
</blockquote></details>

Done.
___
*[inflight_recording/autovid.service, line 14 at r3](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPu8MP4J5RZF-XLd2h:-MbTV6WZEI-Xp9OygVKb:b-896fix) ([raw file](https://github.com/waterloo-rocketry/daq/blob/fe0db1461142adfe4892414f3df14b3179d97579/inflight_recording/autovid.service#L14)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

`sysinit` is again very early in the setup process, the most common target for things like this is simply `default.target` which is after all of the standard background services that this might depend on have started.
</blockquote></details>

Done.
___
*[inflight_recording/autovid.sh, line 3 at r2](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPDyYC3avxm7OUoDMk:-MbTV7SI83bqdxVaAq9n:b-896fix) ([raw file](https://github.com/waterloo-rocketry/daq/blob/ae1614ba3774932ba86e839f4f30d5c10733700d/inflight_recording/autovid.sh#L3)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> NOW=$(date +%Y%m%d%H%M%S)
> ```
Can you leave a comment with an example of what this format will look like?
</blockquote></details>

Done.
___
*[inflight_recording/autovid.sh, line 7 at r3](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPuhDcEZhhnECRZRpu:-MbTV8vG11GzbPGgMhSi:b-896fix) ([raw file](https://github.com/waterloo-rocketry/daq/blob/fe0db1461142adfe4892414f3df14b3179d97579/inflight_recording/autovid.sh#L7)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Nit, it's good practice to wrap all `$VARIABLE`s in double quotes. You also probably don't need the `-vvv` here given that stdout isn't being logged (which you may want to do anyways, but still `-vvv` is likely unnecessary). Also a comment explaining what the programs making up this pipe all do would be good.
</blockquote></details>

Done.
___
*[inflight_recording/README.md, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPE5c_D-oT7elGtyVc:-MbTVAbQCKdzOV1ycZeU:b-896fix) ([raw file](https://github.com/waterloo-rocketry/daq/blob/ae1614ba3774932ba86e839f4f30d5c10733700d/inflight_recording/README.md#L2)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> HOW SETUP
> ```
`HOW TO SETUP`
</blockquote></details>

Done.
___
*[inflight_recording/README.md, line 25 at r2](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPDj9U0ruz6QYMTRap:-MbTVELu56fA-usyb-fa:b-896fix) ([raw file](https://github.com/waterloo-rocketry/daq/blob/ae1614ba3774932ba86e839f4f30d5c10733700d/inflight_recording/README.md#L25)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> 1. Run `sudo cp autovid.service /etc/systemd/system/`
> 1. Run `sudo systemctl daemon-reload`
> 1. Run `sudo systemctl enable autovid.service`
> ```
Can you add a `setup.sh` script that runs these three commands for convenience?
</blockquote></details>

Done.
___
*[inflight_recording/README.md, line 41 at r2](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPDoP34XB-VDvNvzG6:-MbTVJScDiftrKSC2c85:b-896fix) ([raw file](https://github.com/waterloo-rocketry/daq/blob/ae1614ba3774932ba86e839f4f30d5c10733700d/inflight_recording/README.md#L41)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> is be in
> ```
`is in` or `will be in`
</blockquote></details>

Done.
___
*[inflight_recording/README.md, line 35 at r3](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-MbPvMPYC0xXJyy0-zUc:-MbTVF9z15eK18fRmM8a:b-ovcmzl) ([raw file](https://github.com/waterloo-rocketry/daq/blob/fe0db1461142adfe4892414f3df14b3179d97579/inflight_recording/README.md#L35)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

FTP is classically on port 21, is 22 correct?
</blockquote></details>

22 is correct.

**Review by BluCodeGH — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/11)* status: all files reviewed, 4 unresolved discussions (waiting on @jacobdeery and @ZTeper)

**Review by ZTeper — APPROVED** [review]

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-:-Mbc8BPzEKmMhIaD3P0B:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @chrissank and @jacobdeery)

___
*[inflight_recording/autovid.sh, line 21 at r5](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-Mbc8Jfb8KRGhEiScTvF:-Mbc8Jfb8KRGhEiScTvG:bgcv0cg) ([raw file](https://github.com/waterloo-rocketry/daq/blob/105ec070b5d96f9640a8029c993cd7a66a84c3de/inflight_recording/autovid.sh#L21)):*
> ```
> udp://192.168.1.5:5000
> ```
This should be a variable that the user sets at the top of the file.
___
*[inflight_recording/README.md, line 58 at r5](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-Mbc8bZ5DSFzuDu6fCIq:-Mbc8bZ5DSFzuDu6fCIr:b-g9i552) ([raw file](https://github.com/waterloo-rocketry/daq/blob/105ec070b5d96f9640a8029c993cd7a66a84c3de/inflight_recording/README.md#L58)):*
> ```Markdown
> 1. Transfer the converted files into `autovid` (see `Basic Pi setup` to learn how to transfer files)
> 1. Run `chmod u+x setup.sh`
> 1. Run `./setup.sh` to configure the autovid service
> ```

Add a line about setting the IP to stream to.
___
*[inflight_recording/README.md, line 83 at r5](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-Mbc9PAJ9cUOWSr4ctaX:-Mbc9PAJ9cUOWSr4ctaY:b-mk6vqf) ([raw file](https://github.com/waterloo-rocketry/daq/blob/105ec070b5d96f9640a8029c993cd7a66a84c3de/inflight_recording/README.md#L83)):*
> ```Markdown
> ## Extra Details
> 
> If lagging occurs, it may be possible that the `gpu_mem` component of `/boot/config.txt` needs to be upped to 264. We upped it on the original, but did not test if it was required (as it turned out another issue was the problem)
> ```

264 -> 256

**Review by chrissank — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/11)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @BluCodeGH and @jacobdeery)

___
*[inflight_recording/autovid.sh, line 21 at r5](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-Mbc8Jfb8KRGhEiScTvF:-MbcMzC_-tEmcwpLG7d9:b-896fix) ([raw file](https://github.com/waterloo-rocketry/daq/blob/105ec070b5d96f9640a8029c993cd7a66a84c3de/inflight_recording/autovid.sh#L21)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

> ```
> udp://192.168.1.5:5000
> ```
This should be a variable that the user sets at the top of the file.
</blockquote></details>

Done.

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r4, 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/daq/11#-:-MbcNYhmC3LyRMfClB5Z:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @jacobdeery)

**Pull request merged**
